version: "3.3"

services:
  backend:
    build: ./backend
    image: backend
    container_name: backend
    depends_on:
      - database
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - front-back
      - back-db
    volumes:
      - ./backend:/usr/src/app

  database:
    image: postgres
    container_name: database
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - back-db
      - db-admin
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - db-admin
    ports:
      - 5050:80
    logging:
      driver: none

  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - front-back
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

volumes:
  data_database:

networks:
  db-admin:
    driver: bridge
    name: db-admin

  back-db:
    driver: bridge
    name: back-db

  front-back:
    driver: bridge
    name: front-back
